# Generated by Django 6.0.2 on 2026-03-06 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_address_country_alter_cart_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ('-updated_at',)},
        ),
        migrations.AddField(
            model_name='address',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address Description'),
        ),
        migrations.AddField(
            model_name='address',
            name='area',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Area'),
        ),
        migrations.AddField(
            model_name='address',
            name='building_no',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Building / House No / Floor / Street'),
        ),
        migrations.AddField(
            model_name='address',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Full Name'),
        ),
        migrations.AddField(
            model_name='address',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='address',
            name='province',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Province'),
        ),
        migrations.AddField(
            model_name='address',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(default='Pakistan', max_length=150, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='address',
            name='locality',
            field=models.CharField(max_length=150, verbose_name='Colony / Suburb / Locality / Landmark'),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='State'),
        ),
    ]
