# Generated by Django 6.0.2 on 2026-03-08 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_companyinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Product rating from 0 to 5 stars', max_digits=3),
        ),
    ]
