# Generated by Django 6.0.3 on 2026-03-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_order_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Brand Name'),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_time',
            field=models.TextField(blank=True, help_text='Estimated delivery time range (e.g., 2-3 working days)', null=True, verbose_name='Delivery Time Info'),
        ),
        migrations.AddField(
            model_name='product',
            name='enable_facebook_share',
            field=models.BooleanField(default=True, verbose_name='Enable Facebook Share'),
        ),
        migrations.AddField(
            model_name='product',
            name='enable_linkedin_share',
            field=models.BooleanField(default=True, verbose_name='Enable LinkedIn Share'),
        ),
        migrations.AddField(
            model_name='product',
            name='enable_pinterest_share',
            field=models.BooleanField(default=True, verbose_name='Enable Pinterest Share'),
        ),
        migrations.AddField(
            model_name='product',
            name='enable_twitter_share',
            field=models.BooleanField(default=True, verbose_name='Enable Twitter/X Share'),
        ),
        migrations.AddField(
            model_name='product',
            name='refund_and_return_policy',
            field=models.TextField(blank=True, help_text='Information about return and refund policies', null=True, verbose_name='Refund & Return Policy'),
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.TextField(blank=True, help_text='Enter sizes separated by comma (e.g., S, M, L, XL or 36, 38, 40)', null=True, verbose_name='Available Sizes'),
        ),
    ]
