# Generated by Django 6.0.2 on 2026-04-20 22:56

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_product_brand_product_delivery_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='detail_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
